# Name of workflow
name: install-lint-test

# Trigger the workflow on push or pull request
on:
  - push

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
        # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        # Step's name
      - name: Setup PHP
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '8.4'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint
      - name: Run tests
        # Run Tests
        run: make test
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      # NOTE: uncomment for using workflow
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
      #   # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true